#!/bin/bash
# A mocked version of docker for dockhack's tests.

readonly TEST_ID=f0e4fa5fd7052fdc5db8561ed6fbb38dd7c7d21e9654b246316048beef1ab7ac
readonly TEST_NAME=test_container
readonly TEST_IP="172.17.0.4"
readonly TEST_ROOTPID=2323

case "$@" in
    "ps -l -q --no-trunc")
        echo "$TEST_ID"
        ;;
    "inspect --format {{.NetworkSettings.IPAddress}}"*)
        echo "$TEST_IP"
        ;;
    "inspect --format {{.State.Pid}}"*)
        echo "$TEST_ROOTPID"
        ;;
    "inspect --format {{.ID}}"*)
        echo "$TEST_ID"
        ;;
    *)
        # no-op
        ;;
esac


